version: 0.0
os: linux
files:
  - source: /cmd/cmd
    destination: /shortener
  - source: /tmpl
    destination: /shortener/tmpl
hooks:
  BeforeInstall:
    - location: scripts/go.sh
    - location: scripts/build.sh
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 3600
